.TH CLIP_INSTALL_CONF 5 "JUNE 2007" Linux "Programmer's Manual"
.SH NAME
clip_install.conf \- The configuration file of 
.B clip_install 
(8)
.SH SYNOPSIS
.B /etc/clip_install_clip_core.conf

.B /etc/clip_install_clip_apps.conf

.B /etc/clip_install_rm_core.conf

.B /etc/clip_install_rm_apps.conf

.SH DESCRIPTION
This manual page describes the format of the
.B clip_install.conf
file. This file is a simple text file that gives the parameters used by the
.B clip_install
(8) tool. For each parameter a single line should be present with the following information:
.RS
.PP
parameter=value
.RE
.PP
where 
.I parameter
is the name of the parameter
and
.I value
is the value of the parameter.

Two parameters are currently defined :
.PP
\- 
.B option_force
: if set to 
.I yes,
the packages dependencies will not be checked during the installation process and packages whose signature is wrong will not be removed from the 
.B clip_install
packages cache.
.PP
\- 
.B option_install_high_impact_packages
: if set to 
.I yes, 
the packages whose impact is high will be installed by 
.B clip_install.
.PP
The file is named after the distribution and the part concerned : 

.B - /etc/clip_install_clip_core.conf
for the
.I core
part of the
.I clip
distribution.

.B - /etc/clip_install_clip_apps.conf
for the
.I apps
part of the
.I clip
distribution.

.B - /etc/clip_install_rm_core.conf
for the
.I core
part of the
.I rm
distribution.

.B - /etc/clip_install_rm_apps.conf
for the
.I apps
part of the
.I rm
distribution.

.SH AUTHORS
EADS Defence And Security Systems
.SH SEE ALSO
.BR clip_install (8)
